export const OBTENERPRODUCTOS= "OBTENERPRODUCTOS"
export const OBTENERDETALLES="OBTENERDETALLES"

export const LOGIN_EXITO="LOGIN_EXITO"
export const LOGIN_ERROR="LOGIN_ERROR"
export const REGISTRO_EXITO="REGISTRO_EXITO"
export const REGISTRO_ERROR="REGISTRO_ERROR"
export const CERRAR_SESION="CERRAR_SESION"

export const CART_ADD_ITEM='CARD_ADD_ITEM'
export const CART_REMOVE_ITEM='CART_REMOVE_ITEM'

export const OBTENER_ORDEN="OBTENER_ORDEN"
export const CREAR_ORDEN="CREAR_ORDEN"
export const PAGAR_ORDEN="PAGAR_ORDEN"
export const PAGAR_ORDEN_ERROR="PAGAR_ORDEN_ERROR"
