export const OBTENERPRODUCTOS= "OBTENERPRODUCTOS"
export const OBTENERDETALLES="OBTENERDETALLES"

export const LOGIN_EXITO="LOGIN_EXITO"
export const LOGIN_ERROR="LOGIN_ERROR"
export const REGISTRO_EXITO="REGISTRO_EXITO"
export const REGISTRO_ERROR="REGISTRO_ERROR"
export const CERRAR_SESION="CERRAR_SESION"